CREATE TABLE `task` (
  `int_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` varchar(64) NOT NULL,
  `name` varchar(64) NOT NULL COMMENT '工单名称',
  `creator_id` varchar(64) NOT NULL COMMENT '创建工单用户',
  `user_id` varchar(64) NOT NULL COMMENT '接单用户',
  `address` text  COMMENT '工单地址',
  `location` json  COMMENT '派单地点',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=待接单；1=已接单；2=已签到；3=已签出',
  `level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=一般；1=紧急',
  `active_at` datetime DEFAULT NULL COMMENT '接单时间',
  `check_in_at` datetime DEFAULT NULL COMMENT '签到时间',
  `check_out_at` datetime DEFAULT NULL COMMENT '签出时间',
  `description` text  COMMENT '工单说明',
  `comment` text  COMMENT '接单人评论',
  `check_range` float(10,2)  COMMENT '有效打卡半径',
  `active_location` json  COMMENT '接单地点',
  `check_in_location` json  COMMENT '签到地点',
  `check_out_location` json  COMMENT '签出地点',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`int_id`),
  UNIQUE KEY `u_id` (`task_id`),
  KEY `creator_id` (`creator_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='task'